### PR TITLE
Vue 3 support

### LINKED ISSUE #8: Getting Error Cannot read properties of undefined (reading '_c')
Hi, I'm using it like the documentation, and i'm getting this error: 
```
vue-gpickr.umd.min.js?31f7:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.a (vue-gpickr.umd.min.js?31f7:1:1)
    at renderComponentRoot (runtime-core.esm-bundler.js?5c40:464:1)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js?5c40:4332:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js?a1e9:160:1)
    at setupRenderEffect (runtime-core.esm-bundler.js?5c40:4458:1)
    at mountComponent (runtime-core.esm-bundler.js?5c40:4241:1)
    at processComponent (runtime-core.esm-bundler.js?5c40:4199:1)
    at patch (runtime-core.esm-bundler.js?5c40:3791:1)
    at mountChildren (runtime-core.esm-bundler.js?5c40:3987:1)
    at mountElement (runtime-core.esm-bundler.js?5c40:3896:1)
```

I'm working in Vue3

### PR DESCRIPTION
**Pull request by EdwinHoksberg**
It was pretty easy to port this library to Vue 3, I only had to change a few things:
- Update `value` to `modelValue` in the vue component (https://v3.vuejs.org/guide/migration/v-model.html#v-model)
- Remove private class variables as they are incompatible with the new Vue 3 proxy model (https://github.com/tc39/proposal-class-fields/issues/106)
- Update the `vue-color` package to use a Vue 3 fork (https://github.com/ckpack/vue-color)
- Fix deprecation of `::v-deep` style selector (https://github.com/vuejs/rfcs/blob/master/active-rfcs/0023-scoped-styles-changes.md)

I'm not sure what the best course of action is to create a new Vue 3 release for this package, since the current tag is `0.4.2` maybe we should bump that to `1.0` when this gets merged?

Fixes #8

### CODE REVIEW

**Comment by insky** [comment]
I must think how to deal with Vue2 projects that use this library. Any thoughts?

**Comment by EdwinHoksberg** [comment]
I think we can do something like what https://github.com/Norserium/vue-advanced-cropper is doing, they have a `master` branch that targets Vue 2 and a `vue-next` that targets Vue 3. Looking at their versions in npmjs(https://www.npmjs.com/package/vue-advanced-cropper) they have two current tags, `latest`(which is version `1.x`) and `next`(which is `2.x`).

I don't know how this tagging and releasing works in the npmjs registry, but does this sound like a good idea to you?

**Comment by andaonlinefundraising** [comment]
Any update on this? :)

**Comment by insky** [comment]
O, so sorry. I need more time. Right now my country defending russian invasion, so I'm a little busy now. Hope in few days I'll return to your problem.
Glory to Ukraine!

**Comment by aloisdg** [comment]
This PR is currently [high](https://news.ycombinator.com/item?id=30500669) on HN. @insky you may want to lock it to prevent spam.

**Comment by JesseTG** [comment]
> Any update on this? :)

Read the room, please.

**Comment by envp** [comment]
> This PR is currently [trending](https://news.ycombinator.com/item?id=30500669) on HN. @insky you may want to limit it to contributors to prevent spam. AFAIK, locking wont limit emoji reaction (which is a nice thing if people wants to show support)

I think that would be a good decision, trending issues tend to invite comments which eventually become a moderation burden.

**Comment by iamricks** [comment]
Good luck @insky ❤️

**Comment by gjsman** [comment]
War makes everything else quickly seem insignificant.

God be with you @insky, may you return home safely and victorious.

**Comment by jandrusk** [comment]
> This PR is currently [trending](https://news.ycombinator.com/item?id=30500669) on HN. @insky you may want to [limit it to contributors](https://docs.github.com/en/communities/moderating-comments-and-conversations/locking-conversations) to prevent spam. Locking may limit emoji reaction though (which will block people who wants to show their support)

Long live Ukraine!

**Comment by deedubs** [comment]
@insky: I don't need your PRs, I need ammo

**Comment by pmarreck** [comment]
given that programmers are from everywhere now, and the vast majority of us are anti-war, I wonder what glories might happen if we combined forces...

Good luck @insky , Putin's going to suffer for this. Unfortunately, this is now going to dominate this PR thanks to HN. Please don't lock

**Comment by MaKiPL** [comment]
Is there a way to enumerate and see "laugh" emote users? That would be great to have a list of shame so everyone could source from it to block them

**Comment by timweissenfels** [comment]
Hey, good luck with defending your Country ❤️

**Comment by Apacher122** [comment]
> O, so sorry. I need more time. Right now my country defending russian invasion, so I'm a little busy now. Hope in few days I'll return to your problem. Glory to Ukraine!

Genuinely hope you're okay brother! Godspeed!

**Comment by RollingTL** [comment]
> O, so sorry. I need more time. Right now my country defending russian invasion, so I'm a little busy now. Hope in few days I'll return to your problem.
Let me express my admiration to brave people of Ukraine. I wish you victory. Kazakh people really understand the evil your are fighting with. 
Sorry for offtopic fellow  developers. For several days I read all about this war but this comment made me literally cry.

**Comment by batisteo** [comment]
### ✅ This branch has no conflicts with the base branch

Let’s make it that way IRL

**Comment by lmaydev** [comment]
Russia thought they could just rebase and be done with it.

They didn't count on so many merge conflicts.

Stay safe my friend.

**Comment by alsoknownasdrew** [comment]
Героям слава!

**Comment by theunixman** [comment]
slava ukraine!

**Comment by adennnn** [comment]
> O, so sorry. I need more time. Right now my country defending russian invasion, so I'm a little busy now. Hope in few days I'll return to your problem. Glory to Ukraine!

It is unfortunate. Glory to ukraine!!! <3 ukraine

**Comment by Ancientkingg** [comment]
I wish you and your country nothing but safety and prosperity ❤️

**Comment by lloydjatkinson** [comment]
🇺🇦

**Comment by insky** [comment]
Thank you, guys. Can I ask for your help? Russian fake sites must be DDOS-ed.
https://github.com/almerico/bombardier
Thanks forehead for any help

**Comment by lloydjatkinson** [comment]
🇺🇦 ❤️

**Comment by jonstorer** [comment]
Good luck @insky 🇺🇦

**Comment by jandrusk** [comment]
Don't worry, Putin's TTL is getting shorter each day. 😂

**Comment by steven-tey** [comment]
You're a legend, @insky!! Слава Україні! 🇺🇦

**Comment by julianfairfax** [comment]
Slava Ukraini! ukraine

**Comment by InternationalYear204** [comment]
Слава Украине!  Путин на хуй! 🇺🇦

**Comment by stingalleman** [comment]
Slava Ukraini! Heroiam slava! 🇺🇦

**Comment by ncastro-evidation** [comment]
Gloria a Ukrania!! 🇺🇦🇺🇦🇺🇦

**Comment by Gehhilfe** [comment]
🇺🇦♥️

**Comment by ronganEnerknol** [comment]
Glory to Ukraine and Ukrainian people

**Comment by mayaverakustomer** [comment]
🇺🇦 Слава Украине! 🇺🇦

**Comment by LuisO420** [comment]
Слава Украине

**Comment by esantoro** [comment]
Слава Україні! / Slava Ukraini!

**Comment by reececomo** [comment]
🇺🇦 ❤️ Слава Украине! 🇺🇦

**Comment by ocket8888** [comment]
Російський військовий корабель, іди на хуй

🇺🇦 🇺🇦 🇺🇦

**Comment by piersolenski** [comment]
I don't have any ammo handy but sending love and support.

https://stop-russian-desinformation.near.page/

**Comment by terremoth** [comment]
All the glory to Ukraine, and we hope Russia's and Putin's tyranny ends asap
🇺🇦 🇺🇦 🇺🇦

**Comment by ArdxWe** [comment]
Good Luck @insky

**Comment by Cyebukayire** [comment]
function (@insky){
     return victory
}

**Comment by insky** [comment]
Hi, guys! I’m really touched with huge support and never can imagine such discussions of tiny Vue component PR 😆
Me and my family safe enough for now, but huge part of Ukraine still suffering Russian missiles.
This PR never be closed in memory of this days, but I promise to support repo after the war is over.
Give me know putting “thumb up” if you want me posting here short daily notes.
Glory to Ukraine! Death to enemies! 🇺🇦

**Comment by adamreisnz** [comment]
Russian warship, go F yourself!

All the best to you and your fellow country men and women, @insky.

**Comment by alekrutkowski** [comment]
❤️ to 🇺🇦 from Brussels and 🇵🇱!
Glory to the heroes for stopping 🕱putin🕱 in his attack on Europe.
Our ammo (thanks to the authors, copied from above):
https://github.com/almerico/bombardier
https://stop-russian-desinformation.near.page/

**Comment by vigneshesan** [comment]
May the Force be with You !!!

**Comment by alekrutkowski** [comment]
If you want to make a more tangible contribution:
https://bank.gov.ua/en/news/all/natsionalniy-bank-vidkriv-spetsrahunok-dlya-zboru-koshtiv-na-potrebi-armiyi

**Comment by Aakarshan-chauhan** [comment]
Good Luck.

**Comment by Binozo** [comment]
Slava Ukraini 🇺🇦 ❤️

**Comment by arvind1998** [comment]
This PR is golden! 💛 
Слава Україні! 🇺🇦 The world needs you. 
Love from 🇮🇳

**Comment by arvind1998** [comment]
This PR is golden! 💛
Слава Україні! 🇺🇦 
Love from 🇮🇳

**Comment by ncastro-evidation** [comment]
Viva Ukrania!!! 🇺🇦🇺🇦🇺🇦

**Comment by himark1977** [comment]
You have our full support 🇺🇦🇺🇦🇺🇦

**Comment by insky** [comment]
Hi, guys, many of your wanted me to leave daily reports, so let it be.
I live in Kyiv with my wife and 3 years son. When the war began, I’ve decided to stay home and that was my mistake. When we covered in bombshelter for first time, my son started crying in horror very soon. After that we stayed at home near bearing wall when air strike alarms announced. We made decision to escape Kyiv and move west. At February 26 we leaved Kyiv with sounds of alarms and automatic gun bursts. Now we are still in Ukraine with our relatives near Khmelnitskiy and safe enough.  I’ve tried to join local defense forces, but was rejected, they have enough people, so now I try to do what I can, DDoSing russian sites, supporting my friends, helping refugee families to find shelter.

She you tomorrow!
Glory to Ukraine! 🇺🇦

https://bank.gov.ua/en/news/all/natsionalniy-bank-vidkriv-spetsrahunok-dlya-zboru-koshtiv-na-potrebi-armiyi

**Comment by Himself65** [comment]
hope you're safe🇺🇦

**Comment by theunixman** [comment]
@insky you and all Ukranians are treasures of humanity. Stay safe please! We're doing what we can from here too.

**Comment by insky** [comment]
Hi, today post will be very short, I’m learned everything about tunneling. We dig trenches and made fortifications, I’m dead tired.
Glory to Ukraine! 🇺🇦

**Comment by insky** [comment]
Today is the 3rd birthday of my son Ilya (our form of Elijah). Wish him love and peace.
I’ve ridden car a lot today solving some bureaucratic affairs and trying to find some toys as a birthday gift.
Visiting some places where my childhood and youth passed make me feel some nostalgia.
Glory to Ukraine! 🇺🇦

**Comment by nielsrobin** [comment]
@insky Good luck!

**Comment by theunixman** [comment]
Happy birthday Ilya from someone with the Hebrew name Eliyahu! Slava Ukraine!

**Comment by Alilabib** [comment]
@insky I hope you and your family are safe 🙏

**Comment by insky** [comment]
Today is absolutely useless and non-productive day. Some of our plans for nearest future gone with the wind, I’m feel myself upset and tired. I’m know that such things is a usual psychological fluctuations in stress environment, so I’m just want this day over. See you tomorrow, my friends, hope I’ll be in good mood.
Glory to Ukraine! 🇺🇦

**Comment by alekrutkowski** [comment]
You are titans! Glory to Ukraine, glory to the heroes! The evil empire will fall! Don't give up!
Belated happy birthday to your son!
I've copied the "stop propaganda" page to my home server:
https://shiny-r.tk/stop.html
(https://stop-russian-desinformation.near.page/ appears to be down).
Use it before 💩poo-tin💩 scum find it (it will re-emerge somewhere anyway).

**Comment by bardware** [comment]
> Glory to Ukraine!

https://github.com/fre5h/DoctrineEnumBundle/pull/12#issuecomment-33023169

Good luck!

**Comment by UmbReTHY** [comment]
War is horrible. I hope it will end soon, and that the civilians are being kept out of it until the end, like it is mostly happening now.
The hypocrisy of some of you is astounding. Where were you all these years during the invasions of Afghanistan (20 years!), Iraq, Syria, Libya, Yemen, Pakistan, Somalia and Uganda?
Some of these are still ongoing - where is your support for the attacked countries? The hundreds of thousand innocent dead people? I may have misheard it, but I did not hear your loud unison against "the evil empire".
Well done, western media. And no, I do not support the invasion at all - or any invasion.
Some of you should maybe ask themselves, why this foreign conflict is brought to so much attention to you? Could it be a distraction from all the covid fraud? The bad polls of your president puppet? A convenient reordering of oil/gas delivery contracts (cheap russian stuff vs. expensive(!) and environmently bad fracking stuff from US - well done EU ...)? A convenient explanation for financial breakdown? So many winners ... I thought my fellow programming comrades would be a little more capable of critical thinking ...
God bless.

**Comment by laurent22** [comment]
Wrong forum @UmbReTHY. You might want to try your luck at /r/im14andthisisdeep/

**Comment by terremoth** [comment]
> War is horrible. I hope it will end soon, and that the civilians are being kept out of it until the end, like it is mostly happening now. The hypocrisy of some of you is astounding. [...]

@UmbReTHY most of us knows that. USA is not the "big hero" of the humanity and did a lot bad things already (still doing sometimes), and we all know its gas/oil and $$$ interest at this point there. 

The point here is: we do not support a country just enter inside another and kills innocent people and throws bombs. That's not right. 
You can tell "ah but what about conflicts at syria, lybia, etc etc etc" there were a lot of conflicts in the world, lots of them right now. People are not obliged to know all the causes and consequences of each one, and the *MOTIVES* of *EACH* these conflicts are far different, some are barely noticed in the mainstream media. You have no right to judge people's behavior here. 
We are united here in peace trying to make the world a better place, this is a software development platform, not twitter. I suppose most of the people reading this does not support war in any case.

**Comment by defigor** [comment]
Slava Ukraine!

**Comment by flads** [comment]
Brazil is with Ukraine!

**Comment by Rongeegee** [comment]
Slava Ukrane

**Comment by alekrutkowski** [comment]
Yes, indeed, it makes total sense. A well-known US agent (a bot? a botox-beauty?) v_poo_tin, inspired by a well-known promoter of dirty American oil gerhard_schröder, invaded Ukraine to force Europe stop accepting the green eco-friendly synthetic Russian sunflower oil from high-tech non-profit labs in Siberia. Helpless unarmed Russian soldiers are being bombed by imperialist Ukrainian children located in the basements of heavily fortified hospitals and kindergartens. Luckily, we have the Ministry of Truth in Russia (phone number: 1984) which helps Russian media to heroically ignore mentioning that "non-war" in their news, so the flourishing Russian democracy is luckily not in danger – all the polls and elections in Russia show that their leaders are supported by 123% of the Russian population, unlike in totalitatrian US and EU suppressing the freedom of speech. We should of course follow and ignore this non-invasion like we did when aggressive Syrian civilians attacked peaceful Russian visitors. And yes, there is no Covid either, Sputnik-V told me. 5 + 7 = −3

**Comment by UmbReTHY** [comment]
> Yes, indeed, it makes total sense. A well-known US agent (a bot? a botox-beauty?) v_poo_tin, inspired by a well-known promoter of dirty American oil gerhard_schröder, invaded Ukraine to force Europe stop accepting the green eco-friendly synthetic Russian sunflower oil from high-tech non-profit labs in Siberia. Helpless unarmed Russian soldiers are being bombed by imperialist Ukrainian children located in the basements of heavily fortified hospitals and kindergartens. Luckily, we have the Ministry of Truth in Russia (phone number: 1984) which helps Russian media to heroically ignore mentioning that "non-war" in their news, so the flourishing Russian democracy is luckily not in danger – all the polls and elections in Russia show that their leaders are supported by 123% of the Russian population, unlike in totalitatrian US and EU suppressing the freedom of speech. We should of course follow and ignore this non-invasion like we did when aggressive Syrian civilians attacked peaceful Russian visitors. And yes, there is no Covid either, Sputnik-V told me. 5 + 7 = −3

You can twist my words all you want. Good for you. But at the end of the day you would have to admit that you did not know about the 14k+ dead people since 2014 in eastern Ukraine killed by Nazi battalions (e.g. Azov ). I did not know either. (https://youtu.be/sy759dlJWYE, use English subtitles). No one in the western world, me included cared about these people. I also did not know that NATO pumped massive amounts of weapons into Ukraine, or funded at least 7 bio-weapon-research facilities. Selenzky hinted to cancel the Budapest memorandum on Feb 19th, 2022 which would then enable Ukraine to amass nuclear weapons. The narrative prior to the conflict in western media was: "Ukraine is sovereign, and can join NATO if it wants to. Russia would have to accept that." Oh, really? Just imagine Russia making agreements with Mexico, Cuba or Canada in joining an alliance and stationing nuclear weapons around US territory? Sure the U.S. would accept that sovereign decision of its neighbors ...
And no, the economical profits of third parties were (maybe? what do I know) not the motivation to escalate the situation prior to the military intervention as you twist my words here, but of course everyone is trying to reap as much benefit of the situation as possible now that has happened.
As always, when global players play chess, the general populous is going to be the pawn sacrifice.

**Comment by nielsrobin** [comment]
@insky Slava Ukraini. I wish you and your family well and hope you and your country make it out of this Russian aggression somehow. But it might be time to close down this PR, wish I could continue to get updates from you, but it's clearily being brigadier by russian trolls trying to spread misinformation.

**Comment by MarcosBL** [comment]
Really hope you and your family are safe. Good luck Ukraine ! :ukraine:

**Comment by insky** [comment]
Today is 12th day of war. Ukrainian army successfully restrains occupants, Glory to the Heroes!
Yesterday  I’ve missed post because I’ve looking for new place to stay. We need move further ‘cause of some circumstances.

Glory to Ukraine! 🇺🇦

**Comment by pmarreck** [comment]
@UmbReTHY Surely, 900 Azov members IN TOTAL and the "mere threat" of joining NATO justifies the warring against an entire peaceful European democracy and the slaughtering and terrorizing of innocents by an ex-Stasi/KGB asshole, right? GTFO. Our first mistake was doing business with communists and thus enriching their non-democratically-elected leaders. As soon as Ukraine joins NATO, Russia can go EABOD.

> covid fraud

You mean the absolutely ridiculous difference between the official Russian COVID death toll and the best estimate according to excess deaths? That fraud? https://imgur.com/a/eDw8WaK taken from https://www.economist.com/graphic-detail/coronavirus-excess-deaths-estimates (Sidenote, the actual worldwide number is probably at least 20 million deaths)

May this latest nightmare end soon.

**Comment by theunixman** [comment]
Слава Украине

**Comment by insky** [comment]
Hi, guys. I’m really don’t want to moderate this thread, but in future all anti-Ukrainian lunges will be removed.  à la guerre comme à la guerre.

Today I’ve planned my tomorrow route and settled refugee family. They fleed from Zaporizhzhia region and told me horrible things.

Glory to Ukraine! 🇺🇦

**Comment by theunixman** [comment]
@insky godspeed to you and yours!

**Comment by insky** [comment]
My plans destroyed again by circumstances, it has become a habit.
Today I moved to my parent’s flat for one night. In grocery store I’ve unexpectedly met my old friend from Kyiv, we played in one metal band many years ago. He is on the road to the west. Probability of such meeting very close to zero, it makes me funny.

Oh, yea, I’ve didn’t told you yet, I’m playing bass in two metal bands 😁

Glory to Ukraine! 🇺🇦

**Comment by aloisdg** [comment]
🤘 Dawn Of Victory 🤘

**Comment by piersolenski** [comment]
@insky what are your metal bands called? have they got any stuff online? best wishes and Slava Ukraine! 🫂

**Comment by insky** [comment]
> @insky what are your metal bands called? have they got any stuff online? best wishes and Slava Ukraine! 🫂
“Pomsta” and “Exact Division”
Both of them are on Apple and Google music, Spotify and other main platforms

**Comment by insky** [comment]
Yesterday we moved to Ivano-Frankivsk, my former classmate give us a shelter. At the early morning russian missiles strikes an airports of Ivano-Frankivsk, Lutsk and Dniper. This monsters fires civilians. I have no words to describe what I feel.

Glory to Ukraine! 🇺🇦
Death to the enemies!

**Comment by insky** [comment]
Yesterday evening we arrived in small town of Morshyn famous of its mineral water. We’ll stay here for a long time (if our luck doesn’t fail). Today my son played on the playground with other children for the first time in two weeks. I'm planning to return to work as soon as possible.

Glory to Ukraine! 🇺🇦

**Comment by theunixman** [comment]
Слава Украине товарищ

**Comment by theunixman** [comment]
slava ukraine!

**Comment by alekrutkowski** [comment]
Слава Україні! Chwała Ukrainie! 🇺🇦🇵🇱
Victory to the Heroes! The dark 💀putinist-russian💀 tyranny will suffer an enormous defeat, their increasing genocidal attacks on civilians are a symptom of the fear of the impending collapse.

**Comment by MaximeCrp** [comment]
> Today 21st day of war, more than 100 children killed by russian soldiers, 21 hospitals and 2700 houses destroyed. More than 70% of russian people encourage war. Russia have no forgiveness.
> 
> Glory to Ukraine! 🇺🇦 Death to the enemies!

any updates on your side @insky ?

**Comment by insky** [comment]
Hi, guys. We are still in Morshyn, every night and day here are multiple air raid alerts, fortunately without strikes. Some regions including Kyiv sufferers from massive missile and artillery attacks. Looks like russia wants to fight all civilized world.

I’ve almost returned to my main job, our team is developing cross-chain DeFi application. It’s very hard to dive in work, there isn’t  any table, nearby cafeterias are overcrowded and l must work on a chair or on a bed.

Glory to Ukraine! 🇺🇦

**Comment by insky** [comment]
Month ago the war has begun. Ukraine successfully defending against the world’s second strongest army. Our people are united as never before and victory will be ours at the cost of great grief.

I’m going to visit a military office tomorrow and maybe  join our army. I’m a reserve officer with no combat experience so I can be called to training center. I have no fear just a huge anger.

Glory to Ukraine! 🇺🇦
Death to the enemies!

**Comment by theunixman** [comment]
@insky good on you mate! As the russians are showing the world there's a lot of value in non combat roles, and the largest modern armies have something like 1:3 "tooth to tail". It looks like the Russians have the opposite. Please stay as safe as you can, and fight hard for you and yours.

**Comment by insky** [comment]
Hi, guys. Today I was at the military office third time and was postponed again. There are a lot of volunteers willing to join the army forces to defend Ukraine. Also, a lot of volunteers help supply military and medics, shelter and feed refugees, donate, etc. Russia shows all its monstrosity, deceit and lack of common sense.

Glory to Ukraine! 🇺🇦

**Comment by mar10p** [comment]
Best wishes and stay safe @insky! 🇺🇦

**Comment by insky** [comment]
April 14, day 50

The whole world shuddered from the atrocities of the russians. They used chemical, shrapnel, ignition, and thermostatic bombs, shelling hospitals, schools, and residential buildings. They killed, tortured, and raped civilians, even children.
Russian propaganda machine putting a lot of effort to spread fake information to hide their crimes.

Me and my family still in the town of Morshyn. I visited a military office again and again was postponed. Still attempting to return to a normal work schedule, but with no success.

Glory to Ukraine! 🇺🇦
Death to the enemies!

**Comment by insky** [comment]
June 3, day 100

To recap, Russia have failed at almost any of the initial goals, has shown itself a nation of fascists, the world has identified the problem and has united to help Ukraine, albeit not without gas-chortling feet draggers, particularly within the EU. Ukrainians are incredibly brave and strong, and the Ukrainian military has suddenly shown itself as one of the world's most strongest even with very limited and outdated military technology.

Couple days ago we've returned back home, to Kyiv. Very depressive to see destroyed and burned buildings, broken tanks, destroyed roads and bridges around the city. Standing in lines for gasoline and diesel can take up to several hours. But we at home and we are alive.

Glory to Ukraine! 🇺🇦
Death to the enemies!

**Comment by insky** [comment]
Updated to Vue 3.
PR was automatically closed, can't reopen it

**Comment by theunixman** [comment]
Thank you Insky! Hang in there friend!

**Pull request merged**
